apiVersion: apps/v1
kind: Deployment
metadata:
  name: test123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test123
  template:
    metadata:
      labels:
        app: test123
        version: IMAGE_LABEL
    spec:
      containers:
      - name: test123
        image: ACR_URL/test123:IMAGE_LABEL
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: test123
spec:
  type: NodePort
  selector:
    app: test123
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test123
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  # https://docs.microsoft.com/en-us/azure/aks/http-application-routing
  - host: test123.AKS_URL
    http:
      paths:
      - backend:
          serviceName: test123
          servicePort: 80
        path: /